---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: platformengineering/concourse-ansible-resource
    tag: "latest"

run:
  path: ansible
  args:
  - -c
  - local
  - -m
  - setup
  - all

